# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nv/backend.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nv/backend.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10nv/backend.proto\"\"\n\x13VerificationRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"$\n\x12VerificationResult\x12\x0e\n\x06result\x18\x01 \x01(\t2K\n\x0cVerification\x12;\n\x0cverification\x12\x14.VerificationRequest\x1a\x13.VerificationResult\"\x00\x62\x06proto3'
)




_VERIFICATIONREQUEST = _descriptor.Descriptor(
  name='VerificationRequest',
  full_name='VerificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='VerificationRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=54,
)


_VERIFICATIONRESULT = _descriptor.Descriptor(
  name='VerificationResult',
  full_name='VerificationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='VerificationResult.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['VerificationRequest'] = _VERIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['VerificationResult'] = _VERIFICATIONRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerificationRequest = _reflection.GeneratedProtocolMessageType('VerificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERIFICATIONREQUEST,
  '__module__' : 'nv.backend_pb2'
  # @@protoc_insertion_point(class_scope:VerificationRequest)
  })
_sym_db.RegisterMessage(VerificationRequest)

VerificationResult = _reflection.GeneratedProtocolMessageType('VerificationResult', (_message.Message,), {
  'DESCRIPTOR' : _VERIFICATIONRESULT,
  '__module__' : 'nv.backend_pb2'
  # @@protoc_insertion_point(class_scope:VerificationResult)
  })
_sym_db.RegisterMessage(VerificationResult)



_VERIFICATION = _descriptor.ServiceDescriptor(
  name='Verification',
  full_name='Verification',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=94,
  serialized_end=169,
  methods=[
  _descriptor.MethodDescriptor(
    name='verification',
    full_name='Verification.verification',
    index=0,
    containing_service=None,
    input_type=_VERIFICATIONREQUEST,
    output_type=_VERIFICATIONRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VERIFICATION)

DESCRIPTOR.services_by_name['Verification'] = _VERIFICATION

# @@protoc_insertion_point(module_scope)
